### ISSUE TITLE
Changing game mode

### ISSUE THREAD

**Issue by Nmi-Armitage** [matthew-humphrey/nmssavetool#11]
After 1.38 update game uses json  `Version` number var to store game mode
(that in my opinion creates confusion between old file format and new)

`Version`|game mode
-|-
4616 |normal mode
5128 |creative mode
5640|survival mode
?|permadead (sorry, never played that mode and don't have save)

Example:
```
{
    "Version": 4616, //normal mode
    "Platform": "Win|Final",
    "PlayerStateData": {
...
```
I ask you to consider the possibility of adding this functionality

**Comment by matthew-humphrey** [comment]
Are you asking me to provide a feature to change the game mode (i.e. Version value)? I figured the version encoding on my own when I was experimenting with the 1.37 experimental release. I was curious how they were determining the mode, so I started some new games in different modes and then used a diff tool to compare them. However, I didn't add a feature to edit this because I was concerned that there might be other, subtle, differences between the game modes. I have made an effort to make sure that my tool does not ever corrupt people's saves, and for those that really want to do something beyond what the tool does directly, they can always use the "decrypt" feature, edit the JSON file, and then use "encrypt" to encrypt it back to whichever save slot they want.

**Comment by Nmi-Armitage** [comment]
Yes, i was asking to add feature for changing the game mode.    
For old save format gamers widely converted game modes by changing file name (instructions was available on Steam and Reddit) - and i never heard about any complaints or about corrupted saves.    

In my experience with save modifications, i I also did not encounter any problems - game recreates internal save structure and deletes redundant objects (more than 6 ships "in freighter hangar"/`ShipOwnership` array and other entities)

**Comment by matthew-humphrey** [comment]
I've added a feature to display the game mode along with the version number. Also, you can decrypt / edit / encrypt to update the game mode as I mention above. Closing this issue.
