### ISSUE TITLE
Update for new game save slot format

### ISSUE THREAD

**Issue by jaszhix** [matthew-humphrey/nmssavetool#9]
Starting with version 1.38 (currently on the [experimental branch on Steam](http://steamcommunity.com/app/275850/discussions/0/1496741765127199235/)), they are changing the slot structure so there is two slots per difficulty, but it doesn't seem like the slot numbers are tied to any difficulty now, they just represent the slots in the game mode select screen (out of a new max of 5), but its still one difficulty per slot - two sub slots for each of those, with a total of 9 possible .hg files.

**Comment by matthew-humphrey** [comment]
Yeah, I'm aware of the changes, although what you describe isn't 100% correct. I've already updated my program accordingly, but I'm still trying to work out some details around how to populate one of the five slots if there isn't already a save file there. Also I need to run through all of the features to make sure everything is still working.

But thanks for posting about it - it's appreciated.

**Comment by waldo3000** [comment]
I think there is an issue with supporting the new save format.  If I play in Normal mode in slot 1 and then create a new Survival game in slot 2, nmssavetool says "No save games found for game slot 2".  I tried on a new game with no manual saves and after playing for a while with auto saves and manual saves.

For debugging purposes, it may be helpful to print out which save files are being read/written in verbose mode.

**Comment by matthew-humphrey** [comment]
I have created a new version of the tool that has more verbose logging. Can you give that a try and send me the output? Also, it would be useful if you could use the new "backupall" command, which will backup ALL your save games, and send me the resultant zip file. I have had a real challenge testing NMS 1.38 because I have such a limited number of game saves. The new release is here:
https://github.com/matthew-humphrey/nmssavetool/releases/tag/v2.0.1.2-alpha

**Comment by Raventara** [comment]
Verbose output from maxslots:

> PS C:\Users\russell\Downloads\nmssavetool212a> .\nmssavetool.exe maxslots -g 1 -v
> CLR version: 4.0.30319.42000
> APPDATA folder: C:\Users\russell\AppData\Roaming
> Using NMS AppData folder: C:\Users\russell\AppData\Roaming\HelloGames\NMS
> Using save path: C:\Users\russell\AppData\Roaming\HelloGames\NMS\st_76561198001918084
> Reading inventory item list from: C:\Users\russell\Downloads\nmssavetool212a\InventoryItemTypes.csv
> Checking for save games for slot 1
> Reading game save for slot 1 at metadata path = 'C:\Users\russell\AppData\Roaming\HelloGames\NMS\st_76561198001918084\mf_storage.hg', storage path = C:\Users\russell\AppData\Roaming\HelloGames\NMS\st_76561198001918084\storage.hg, and archive number = 0
> Determining save games file locations for slot 1
> Writing game save for slot 1 to metadata path = 'C:\Users\russell\AppData\Roaming\HelloGames\NMS\st_76561198001918084\mf_storage.hg', storage path = C:\Users\russell\AppData\Roaming\HelloGames\NMS\st_76561198001918084\storage.hg, and archive number = 0
> Wrote latest game save for game slot "1"

[nmssavetool-backupall-20171009-221108.zip](https://github.com/matthew-humphrey/nmssavetool/files/1370627/nmssavetool-backupall-20171009-221108.zip)

However when I load there's no changes...

**Comment by waldo3000** [comment]
I tested version 2.0.1.2 with my save files.  Here is the result when I attempt a decrypt using slot 2 - Note that I have explicitly identified the NMS save directory since I have two NMS installations on my PC.

C:\Users\Scott\Desktop\nmssavetool-2.0.1.2-alpha>nmssavetool decrypt --save-dir C:\Users\Scott\AppData\Roaming\HelloGames\NMS\st_76561198336152197 -f ./oSave.txt -g 2 -v
CLR version: 4.0.30319.42000
APPDATA folder: C:\Users\Scott\AppData\Roaming
Using save path: C:\Users\Scott\AppData\Roaming\HelloGames\NMS\st_76561198336152197
Reading inventory item list from: C:\Users\Scott\Desktop\nmssavetool-2.0.1.2-alpha\InventoryItemTypes.csv
Checking for save games for slot 2
Error loading or parsing save file: No save games found for game slot 2

[NMS save 10-10-17.zip](https://github.com/matthew-humphrey/nmssavetool/files/1372367/NMS.save.10-10-17.zip)

**Comment by matthew-humphrey** [comment]
Ok, can you tell me what the names of the save game files in that directory are? I think they may have renamed them in the 1.38 release (based on some data I saw from another user). If so, should be a simple fix.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by waldo3000** [comment]
I attached the backupall file to my previous comment, so the file names are in that.  Here's a link to that info as a jpeg if that helps:

[https://imgur.com/7BMCmZO](url)

Edit: For some reason that link will not work, but you can copy and paste the URL.

**Comment by matthew-humphrey** [comment]
Sorry, was viewing it in email where there are no attachments. Yes, that is the issue. I will fix it this evening. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by matthew-humphrey** [comment]
Updated version that is verified to work with NMS 1.38 is now available. This is a pre-release (beta).

https://github.com/matthew-humphrey/nmssavetool/releases/tag/v2.0.1-beta

**Comment by waldo3000** [comment]
I can confirm that the new version appears to work correctly.  Thanks!

BTW, do you know whether the files named "mf_storage.hg" and "storage.hg" can be removed or are they still used for something?

**Comment by matthew-humphrey** [comment]
You can remove them.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
